sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chandnisuresh/docker-react -f Dockerfile.dev .
  

script:
  - docker run -e CI=true chandnisuresh/docker-react npm run test -- --coverage